# Generated by Django 3.1.5 on 2021-02-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0003_cardspecialequipmentsupplier_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardproviderofconstructionandinstallationworks',
            name='note',
        ),
    ]
