# Generated by Django 3.1.5 on 2021-02-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0004_remove_cardproviderofconstructionandinstallationworks_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardproviderofconstructionandinstallationworks',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
