# Generated by Django 3.1.4 on 2020-12-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('lastName', models.CharField(max_length=25, verbose_name='Имя')),
                ('adress', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адресс')),
                ('telephone', models.CharField(max_length=10, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Counterparty')),
            ],
        ),
    ]
