# Generated by Django 3.1.5 on 2021-03-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='middleName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='firstName',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='lastName',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='telephone',
            field=models.CharField(max_length=16, unique=True, verbose_name='Телефон'),
        ),
    ]
